---
- name: Acquire and Set an IP Address
  hosts: all
  gather_facts: no
  vars:
  - ip_addr: 192.168.2.67
  - netmask: 24
  - gateway: 192.168.2.254
  - manageiq_validate_certs: false
      
  roles:
    - syncrou.manageiq-vmdb
     
  tasks:
  - debug: var=miq_provision_id
  - debug: var=miq_provision_request_id
    
  - name: Update Request with new IP and Hostname Information
    manageiq_vmdb:
      href: "provision_requests/{{ miq_provision_request_id }}/request_tasks/{{ miq_provision_id }}"
      action: edit
      data:
        options:
          addr_mode: ["static", "Static"]
          ip_addr: "{{ ip_addr }}"
          subnet_mask: "{{ netmask }}"
          gateway: "{{ gateway }}"
  