---
- name: Get lsblk output and return to automation engine
  hosts: all
  
  tasks:
  - name: Connect to VM and run lsblk
    command: /usr/bin/lsblk
    register: lsblk_output
  
- name: Write the lsblk output back to the workspace
  hosts: localhost
  connection: local
  
  vars:
  - manageiq_validate_certs: false
  - auto_commit: true
  
  roles:
  - ansible-role-listvars
  - syncrou.manageiq-automate
  
  tasks:
  - name: Write the lsblk output to a state_var
    manageiq_automate:
      workspace: "{{ workspace }}"
      set_state_var:
        attribute: "lsblk_output"
        value: "{{ lsblk_output }}"


    