---
- name: Save tower job id back to $evm.root
  hosts: all
  connection: local

  vars:
  - manageiq_validate_certs: false
      
  roles:
  - syncrou.manageiq-automate

  tasks:
  - name: "Set the job ID back into $evm.root"
    manageiq_automate:
      workspace: "{{ workspace }}"
      set_attribute:
        object: "root"
        attribute: "tower_job_id"
        value:  "{{ tower_job_id }}"
