---
- name: Test Workspace interaction
  hosts: all
  connection: local
  
  vars:
  - manageiq_validate_certs: false
  - auto_commit: true
  
  roles:
  - ansible-role-listvars
  - syncrou.manageiq-automate

  tasks:
  - name: Retrieve the saved 'date_stamp' state var
    manageiq_automate:
      workspace: "{{ workspace }}"
      get_state_var:
        attribute: "date_stamp"
    register: saved_date_stamp
        
  - debug: var=saved_date_stamp